# Generated by Django 5.0.6 on 2024-08-24 08:50

import ckeditor.fields
import django.db.models.deletion
import magazine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=magazine.models.image_magazine_folder, verbose_name='آیکن')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
            ],
            options={
                'verbose_name': 'دسته بندی مجله ها',
                'verbose_name_plural': 'دسته بندی های مجله ها',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('short_description', models.TextField(blank=True, max_length=250, null=True, verbose_name='توضیحات کوتاه')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=magazine.models.image_magazine_folder, verbose_name='تصویر')),
                ('sort', models.SmallIntegerField(default=0, verbose_name='ترتیب')),
                ('active', models.BooleanField(default=True)),
                ('important', models.BooleanField(default=False, verbose_name='مهم')),
                ('accept', models.BooleanField(choices=[(True, 'تایید'), (False, 'رد')], default=True, verbose_name='نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.magazinecategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مجله',
                'verbose_name_plural': 'مجله ها',
                'ordering': ['sort'],
            },
        ),
    ]
